@baseUrl = http://localhost:8000/api

### Health Check
GET {{baseUrl}}/

###

### People Count
GET {{baseUrl}}/people-counter/count

###

POST {{baseUrl}}/people-counter/count/reset
Content-Type: application/json

{
  "people_count": 0
}

###

POST {{baseUrl}}/people-counter/max-count/reset
Content-Type: application/json

{
  "max_people_count": 10
}